name: Registration_E2E_Test
  
  <!-- Testing 2 yml file-->

on:
   workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: 'Automation.test.RegistrationTests'
      OSRun1:
        required: true
        default: 'ubuntu'
        description: Please select the OS to run test1
        type: choice
        options:
          - windows
          - ubuntu
      BrowserRun1:
        required: true
        default: 'chrome'
        description: Please select the browser to run test1
        type: choice
        options:
          - chrome
          - edge
      OSRun2:
        required: true
        default: 'windows'
        description: Please select the OS to run test1
        type: choice
        options:
          - ubuntu
          - windows
      BrowserRun2:
        required: true
        default: 'edge'
        description: Please select the browser to run test1
        type: choice
        options:
          - chrome
          - edge

   pull_request:
     branches:
       - main

jobs:
  Registration_E2E_First_Test:
    runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-latest' || inputs.OSRun1 == 'ubuntu' && 'ubuntu-latest' || 'windows-latest' }}
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -DBrowserName="${{ github.event_name == 'pull_request' && 'chrome' || inputs.BrowserRun1 }}" -Dtest="${{ github.event_name == 'pull_request' && 'chrome' || inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  Registration_E2E_Second_Test:
    runs-on: ${{ github.event_name == 'pull_request' && 'windows-latest' || inputs.OSRun2 == 'ubuntu' && 'ubuntu-latest' || 'windows-latest' }}
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -DBrowserName="${{ github.event_name == 'pull_request' && 'edge' || inputs.BrowserRun2 }}" -DHeadLessBrowsing="false" -Dtest="${{ github.event_name == 'pull_request' && 'chrome' || inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit